<section class="auth">
    
    <div class="row head">
        <!--logo-->
        <div class="logo"></div>

        <!--menu-->
        <menu>
            <ul>
                <li>
                    <a href="#">o evento</a>
                </li>
                <li>
                    cadastra-se
                    <form action="#" class="sub">
                        <ul class="social">
                            <li>Facebook</li>
                            <li>Google +</li>
                        </ul>

                        <input type="text" placeholder="e-mail" />
                        <input type="password" placeholder="senha" />
                        <button>enviar</button>
                    </form>
                </li>
                <li>
                    já me cadastrei
                    <form action="#" class="sub">
                        <ul class="social">
                            <li>Facebook</li>
                            <li>Google +</li>
                        </ul>

                        <input type="text" placeholder="e-mail" />
                        <input type="password" placeholder="senha" />
                        <button>entrar</button>
                    </form>
                </li>
                <li>
                    <a href="#">contato</a>
                </li>
            </ul>
        </menu>
    </div>

    <div class="row content">
        <h1>BEM VINDO <br>CAMPUSE.RO!<br><br>O QUE VOCÊ PROCURA?</h1>
        <span>não é o que você procura?</span>
    </div>
    
    <footer>"We unite talent. We create the future."</footer>

</section>
