<section class="auth">
    <div class="logo">
        Logotipo
    </div>

    <menu>
        <ul>
            <li>
                <a href="#">o evento</a>
            </li>
            <li>
                cadastra-se
                <form action="#" class="sub">
                    <ul class="social">
                        <li>Facebook</li>
                        <li>Google +</li>
                    </ul>

                    <input type="text" placeholder="e-mail" />
                    <input type="password" placeholder="senha" />
                    <button>enviar</button>
                </form>
            </li>
            <li>
                já me cadastrei
                <form action="#" class="sub">
                    <ul class="social">
                        <li>Facebook</li>
                        <li>Google +</li>
                    </ul>

                    <input type="text" placeholder="e-mail" />
                    <input type="password" placeholder="senha" />
                    <button>entrar</button>
                </form>
            </li>
            <li>
                <a href="#">contato</a>
            </li>
        </ul>
    </menu>
</section>
</section>