
        <aside>
            <h1>Minhas configurações</h1>

            <ul>
                <li>Pesquisar</li>
                <li>Agora na Campus</li>
                <li>Pessoas</li>
                <li>Favoritos</li>
            </ul>

            <ul>
                <li>Agenda Geral</li>
                <li>Workshops</li>
                <li>Challengers</li>
                <li>Talks</li>
            </ul>

            <ul>
                <li>Magistrais</li>
                <li>Palestrantes</li>
                <li>Open Campus</li>
            </ul>

        </aside>


        <section class="posts" style="width:80%;">
            <h1>Agora na Campus</h1>

            <ul>

                <li>
                    <div class="identificacao">
                        <div class="foto"></div>
                        <div class="nome">
                            <h1>Jeferson Rossini</h1>
                            <h3>Campusero</h3>
                        </div>
                        <div class="time">26 min</div>
                    </div>
                    <p>Desafio Open Challenger acontecendo!</p>
                    <div class="acoes">
                        curtidas
                    </div>
                </li>

                <li>
                    <div class="identificacao">
                        <div class="foto"></div>
                        <div class="nome">
                            <h1>Aliberto neto</h1>
                            <h3>Campusero</h3>
                        </div>
                        <div class="time">26 min</div>
                    </div>
                    <p>Desafio Open Challenger acontecendo!</p>
                    <div class="acoes">
                        curtidas
                    </div>
                </li>

                <li>
                    <div class="identificacao">
                        <div class="foto"></div>
                        <div class="nome">
                            <h1>Aliberto neto</h1>
                            <h3>Campusero</h3>
                        </div>
                        <div class="time">26 min</div>
                    </div>
                    <p>Desafio Open Challenger acontecendo!</p>
                    <div class="acoes">
                        curtidas
                    </div>
                </li>

                <li>
                    <div class="identificacao">
                        <div class="foto"></div>
                        <div class="nome">
                            <h1>Aliberto neto</h1>
                            <h3>Campusero</h3>
                        </div>
                        <div class="time">26 min</div>
                    </div>
                    <p>Desafio Open Challenger acontecendo!</p>
                    <div class="acoes">
                        curtidas
                    </div>
                </li>

                <li>
                    <div class="identificacao">
                        <div class="foto"></div>
                        <div class="nome">
                            <h1>Aliberto neto</h1>
                            <h3>Campusero</h3>
                        </div>
                        <div class="time">26 min</div>
                    </div>
                    <p>Desafio Open Challenger acontecendo!</p>
                    <div class="acoes">
                        curtidas
                    </div>
                </li>

                <li>
                    <div class="identificacao">
                        <div class="foto"></div>
                        <div class="nome">
                            <h1>Aliberto neto</h1>
                            <h3>Campusero</h3>
                        </div>
                        <div class="time">26 min</div>
                    </div>
                    <p>Desafio Open Challenger acontecendo!</p>
                    <div class="acoes">
                        curtidas
                    </div>
                </li>

            </ul>
        </section>
