<section class="auth">
    
    <div class="row head">
        <!--logo-->
        <div class="logo_b"></div>

        <!--menu-->
        <menu>
            <ul>
                <li>página do evento</li> 
                <li>network</li>
                <li>contato</li>
                <li>|</li>
                <li>Oi Jeferson</li>
            </ul>
        </menu>
    </div>

    <div class="row content">

        <aside>
            <h1>Minhas configurações</h1>

            <ul>
                <li>Pesquisar</li>
                <li>Agora na Campus</li>
                <li>Pessoas</li>
                <li>Favoritos</li>
            </ul>

            <ul>
                <li>Agenda Geral</li>
                <li>Workshops</li>
                <li>Challengers</li>
                <li>Talks</li>
            </ul>

            <ul>
                <li>Magistrais</li>
                <li>Palestrantes</li>
                <li>Open Campus</li>
            </ul>

        </aside>







        <section class="posts">
            Jef diz
            Jef diz
            Jef diz
        </section>


        <section class="atividades">
            <ul>
                <li ng-repeat="item in items" ng-if="!ativo" style="background-image: url({{item.background_image}})">
                    <div class="desc">
                        <h1>{{item.title}}</h1>
                    </div>
                </li>
            </ul>
        </section>


    </div>
    
    <footer>"We unite talent. We create the future."</footer>
</section>


<!--
<div ng-repeat="item in items" ng-if="!ativo">
    <div class="card">
        <img class="card-img-top" src="{{item.background_image}}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{item.title}}</h5>
            <p class="card-text">{{item.stadium_name}}</p>
            <a ng-click="clickDetalhes(item.slug)" class="btn btn-primary">{{item.event_slug}}</a>
        </div>
    </div>

</div>
<div class="card">
    <img class="card-img-top" src="{{atividade.background_image}}" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">{{atividade.title}}</h5>
        <p class="card-text">{{atividade.stadium_name}}</p>
        <p class="card-text" ng-bind="atividade.description"></p>
    </div>
</div>
-->